services:
  bbb-spd:
    image: inchange.dev/bbb-spd
    volumes:
      - bbb-spd:/app
    networks:
      - traefik-public
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.http.routers.bbb-spd.tls=true
        - traefik.http.routers.bbb-spd.tls.certresolver=cloudflare
        - traefik.http.routers.bbb-spd.rule=Host(`bbb.inchange.dev`)
        - traefik.http.routers.bbb-spd.entrypoints=websecure
        - traefik.http.services.bbb-spd.loadbalancer.server.port=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 2s
      retries: 3

volumes:
  bbb-spd:
    driver: local

networks:
  traefik-public:
    external: true
    driver: overlay
    attachable: true
