name: Build Docker Image

on:
  workflow_call:
    inputs:
      docker_image_name:
        description: "Name of the Docker image to build"
        required: true
        type: string

env:
  DOCKER_IMAGE_NAME: ${{ inputs.docker_image_name }}
  DOCKER_IMAGE_TAG: ${{ GITHUB.SHA }}

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "Building Docker image: ${{ env.DOCKER_IMAGE_NAME }}"
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} --build-arg PORT=3000 .
          echo "Image built successfully"

      - name: Save Docker image
        run: |
          echo "Saving Docker image to tar file..."
          docker save ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} -o ${{ env.DOCKER_IMAGE_NAME }}.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DOCKER_IMAGE_NAME }}
          path: ${{ env.DOCKER_IMAGE_NAME }}.tar
          retention-days: 1

      - name: Cleanup
        run: |
          rm -f ${{ env.DOCKER_IMAGE_NAME }}.tar
          docker rmi ${{ env.DOCKER_IMAGE_NAME }} || true
