name: Build Docker Image

on:
  workflow_call:

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t ${{ vars.DOCKER_IMAGE }}:latest .

      - name: Save Docker image
        run: |
          docker save ${{ vars.DOCKER_IMAGE }}:latest -o ${{ vars.DOCKER_IMAGE }}.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.DOCKER_IMAGE }}
          path: ${{ vars.DOCKER_IMAGE }}.tar
          retention-days: 1
